### ISSUE TITLE
请教一下这个教程的代码在哪...

### ISSUE THREAD

**Issue by duolabmeng6** [WangZhechao/nextjs-demo#1]
https://meishizaolunzi.com/nextjs-markdown-posts/

**Comment by WangZhechao** [comment]
> https://meishizaolunzi.com/nextjs-markdown-posts/

这教程就是我博客，暂时没想放出源码😅，可以按照教程的思路自己搞搞试试，有问题随时可以联系我……

**Comment by duolabmeng6** [comment]
好的 非常感谢你的教程~
